# Generated by Django 3.1.4 on 2021-08-12 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20201006_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='tracker',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package', to='main.tracker', verbose_name='tracker'),
        ),
        migrations.AlterField(
            model_name='package',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='weight'),
        ),
    ]
